### ISSUE TITLE
Vanir industries as defense company idea

### ISSUE THREAD

**Issue by Idhrendur** [RomeStrikesBackMod/RomanHoI4#61]
They were first mentioned in episode 95 of the AAR

**Comment by CaesarVincens** [comment]
Which country? Rome or another?

**Comment by Idhrendur** [comment]
Ah yes, in Rome

**Comment by CaesarVincens** [comment]
Summary of discussion related to Vanir at https://forum.paradoxplaza.com/forum/threads/the-empire-strikes-back-part-3.841253/post-20156026
