### ISSUE TITLE
Characters to add

### ISSUE THREAD

**Issue by Idhrendur** [RomeStrikesBackMod/RomanHoI4#71]
- [x] Andre Massena
  - [x] Sent message
- [x] Arakhor
  - [x] Sent message
- [x] Attalus
  - [x] Sent message
- [x] austrianemporer
  - [x] Sent message
- [x] BBBD316
  - [x] Sent message
- [ ] Beaverman1
  - [x] Sent message
  - [ ] "If its not a bother. I'd like an admiral for Scandinavia named Anders Kvensson 'Duke of Gotland'. I don't much care for how he looks and I'll leave it up to you to decide what traits and skills to give him."
- [x] ByzantineSEA
  - [x] Sent message
- [x] CaterpillarKing
  - [x] Sent message
- [x] CaesarVincens
  - [x] Sent message
- [ ] Cossack_of_Hetmanschina / DerKapitanUnbekannt - Marco Shelepov, General in the military. For portrait, some of the Eastern European ones could work
  - [x] Sent message
  - [x] Confirmed preferences
- [x] Damian0358
  - [x] Sent message
  - [x] Thaddas family
- [x] Figus
  - [x] Sent message
- [x] Fish-Of-Fury
  - [x] Sent message
- [x] GreatUberGeek
  - [x] Sent message
- [x] Michaelangelo - Italy's leader, the bastard son of King Giuseppe Lombard
  - [x] Sent message
- [x] NiccoTesla
  - [x] Sent message
- [ ] oskar-kar - Poland's leader or a significant scientist
  - [x] Sent message
- [x] PrincepsAbsolut
  - [x] Sent message
- [x] righ na-Alba
  - [x] Sent message
- [x] Sakura_F
  - [x] Sent message
- [x] Sancronis
  - [x] Sent message
- [x] Sir Dippingsauce
  - [x] Sent message
- [x] strategymad3500
  - [x] Sent message
- [x] The Crows
  - [x] Sent message
- [x] Username1453
  - [x] Sent message
- [x] volksmarschall
  - [x] Sent message
- [x] zenphoenix - Theodora Doukas, Prime Minister of Rome
  - [x] Sent message

**Comment by Idhrendur** [comment]
Need to contact many people to find out more about their characters. Also need to wait for NSB's character updates and for the converter handling all of that properly.

**Comment by Idhrendur** [comment]
Zen messaged me a potential portrait for Theodora on the forums. Try adding that.

**Comment by CaesarVincens** [comment]
I've got a couple versions, slightly different zooms. I'll post them on the discord for Zen/whoever to review

**Comment by Idhrendur** [comment]
This image for Michaelangelo's [Giuseppe Lombardi](![image](https://user-images.githubusercontent.com/5448596/140854092-46f9bd0a-dca2-4488-9aa8-c2ab2e48f544.png))

**Comment by CaesarVincens** [comment]
Added Giuseppe as the absolutist leader of Italy and a national spirit generally
