### ISSUE TITLE
Aotearoa focus tree

### ISSUE THREAD

**Issue by Idhrendur** [RomeStrikesBackMod/RomanHoI4#73]
Sketch here: https://cdn.discordapp.com/attachments/529487753956818945/904480124374757457/unknown.png
Pastebin with notes here: https://pastebin.com/Hy8cvUCq

**Comment by Idhrendur** [comment]
Thaddai Power Couple [starting national spirit]

The Thaddai family, the Exarchess Kyrene Thaddas, Imperial Representative Nestorius Thaddas, and their son Timon, have been icons of Aotearoa since the formation of the Exarchate. The political advocacy of Kyrene and Nestor would pave the way for not only the reintegration of the islands following the end of the Imperial Civil War of 1910-1913 [dates should be checked], but also the establishment of the Exarchate in the first place, establishing a proper Romanitist government which cares for all inhabitants of the islands. Though getting in age now, they remain the burning heart of the fledgling state.

---

Ol' Ness Hospitalized [event in early 1936]

Nestorius Thaddas has reportedly been hospitalized after a sudden bout of [illness], catching family and friends off alike. Though attempts were made to avoid the spread of this until after it was confirmed what has caused this, newspapers quickly found out and spread the news like wildfire. The public fears for his wellbeing.

'May he soon return to dancing to jazz!'

---

Ol' Ness Has Died! [event in late 1936; rename the focus to "Pizetan Passing']

At around the age of 87, surrounded by friends and family, the Imperial Representative for Aoteorea (and Technical Exarch) Nestorius Thaddas passed away. Emphatic to the core, he would take the reigns as Aotearoa's advocate in his position as Senator, all for the sake of one Māori, the one who now mourns him most. Widely considered the (grand)father of the nation, he will be greatly missed.

'Dear...' [replaces Thaddai Power Couple with Thaddai Heartbreak]

Thaddai Heartbreak [national spirit]

Though the death of Nestorius Thaddas has brought great sadness to the Exarchate, no one has been impacted more by it than our Governess herself. Previously tiredly chipper if worried about the future, Kyrene has increasingly become withdrawn from the public eye, with her staff slowly taking on more and more of her responsibilities. The public worries for what will become of the (grand)mother of the nation, though her staff and son Timon reassures all that she's doing fine.

---

Pizetan Passing [focus; requires Thaddai Heartbreak; reference to when Nestorius was declared 'the Omicron' for his 70th birthday - Pi Zeta / πζʹ / 87]

Though economic questions dominate discourse within the country, with the state of governance, we must begin to consider questions of a political nature, especially in regards to our relationship with the Empire.

---

Send the Boy to Constantinople! [focus]

With the position of Imperial Representative for Aoteorea vacant, and a seat in the Senate left spiritually empty, Timon Thaddas has to travel to the Imperial capital to assert his place as the inheritor of the Thaddai estate, and as Aoteorea's advocate to come!

Timon Thaddas (1) [national spirit]

The son of Nestorius and Kyrene Thaddas, he is abroad representing the interests of not just the Thaddai family, but of all of Aoteorea. Though his connection to his birthplace may be weak in favor of the islands, and he may be timid, but he will do what he can for what he considers his home.

Keep the Boy in Aoteorea! [focus]

With the shock of recent affairs being encumbering, it would be prudent to simply send Timon Thaddas abroad when he may turn out to be more needed in Aoteorea. For the sake of all, we will let those in Constantinople know that they may need to keep the Senatorial seat warm for some time longer.

Timon Thaddas (2) [national spirit]

The son of Nestorius and Kyrene Thaddas, he is presently in Aoteorea, forced into a public position following recent affairs. Though timid, each appearance of his speaks to the love he has for the islands, and the care he has for his fellow countrymen, giving a reassuring feeling to young and old alike.

---

Governess Hospitalized! [late '38 if Timon left, late '39 if Timon stayed?]

To the shock and horror of many, news has come that the Exarchess Kyrene Thaddas has been hospitalized for unknown reasons. Witnesses report that family joined her on her journey to the hospital, keeping her company all the way. With the Exarchess getting in age just like her husband had, the public worries extensively for her wellbeing.

[May her heartbreak recover...]

---

The Governess Has Died! [early '39 if Timon left, early '40 if Timon stayed?]

Surrounded by friends and family, Hairini Waata, Kyrene Udata Thaddas upon marriage, has passed away from stress cardiomyopathy, reportedly induced by the passing of her husband. Caring of family and community, it would be her that would inspire Nestorius to take up the reins of Aoteorea's advocate, and her role as his aid would lead to her being awarded by the Emperor himself the position of Exarchess of her homeland, which she humbly accepted. The (grand)mother of the nation, the people mourn greatly for her and all she had done for the country since 1910, as an advocate and as a leader. She will be missed greatly, as only one Thaddai remains.

'Timon...' [replaces Thaddai Heartbreak with Thaddai Hope]

Thaddai Hope [national spirit]

With the passing of the founding couple of Aoteorea, only one Thaddai remains in this world, that being their son Timon Thaddas. The Exarchate had, to some degree, watched him grow from strength to strength, as it became his home in body and mind. The boy represents, for many, a burning candle flame in treacherous winds. Now both state and he stand young and timid in a changing world, but there remains hope that these are but bumps on the long road ahead. The flame of Aoteorea burns brightly still.

--- / ---

Trauma of Black Thursday [starting national spirit]

Though the economy has long since recovered, the shock of what happened in 1925 with the Black Thursday stock market crash remains in the collective consciousness. With recent global affairs, worry has wormed its way into the minds of many over many aspects of the economy, worry that Black Thursday may come to haunt the Exarchate once more. We must do what we can to overcome the collective trauma the people faced in the state's infancy.

---

Industrial Check-up [focus]

Under the current protectionist, state capitalist system advocated by the Labour Party, checking in on the various industries on the islands is always important. However, this check-up will be key, for it will allow us to consider what course of action to take going forward.

Staunch Anti-Militarists [starting national spirit]

The Labour Party of Aoteorea has implemented a policy of anti-militarism, holding in belief that change is better accomplished through peaceful means, whether through the market or through political action. The pain of the former Imperial Civil War and the Presidential Dictatorship that ruled the islands during it has led to many being in favor of this policy, considering peace to be preferable, and wishing to avoid conflict. How long such a policy may last in the world today, we will soon have to see.

---

The Vulnerable Peace [focus]

With global affairs in mind, the proximity of former and current Imperial rivals to the islands, and even potentially our neighbors, some recognize that the peace we are currently in is vulnerable. As such, something must be decided in order to preserve it by any means.

**Comment by Idhrendur** [comment]
Pictures for characters are on forum around November 3 2021

**Comment by CaesarVincens** [comment]
#79 Includes the starting points for Aotearoa
