### ISSUE TITLE
Niketas Doukas

### ISSUE THREAD

**Issue by Idhrendur** [RomeStrikesBackMod/RomanHoI4#77]
> I'd like to make an in-game character for Niketas Doukas, Theodora's brother and Irene's father.  He'd be a military commander with the traits reckless, politically connected, and brilliant strategist.

**Comment by Idhrendur** [comment]
Possible picture here: https://cdn.discordapp.com/attachments/529488044185747456/532629509753798676/unknown.png

**Comment by CaesarVincens** [comment]
Some options for the portrait
![Quintin4](https://user-images.githubusercontent.com/5217392/141190485-d7dc03f3-64b8-493d-b39a-45c2053deb10.png)
![Quintin3](https://user-images.githubusercontent.com/5217392/141190488-d3eccef5-745d-4a8a-8c3d-276286278dac.png)
![Quintin2](https://user-images.githubusercontent.com/5217392/141190489-b2027c28-dbaa-43a9-932e-48c7e38f19d5.png)
![Quintin1](https://user-images.githubusercontent.com/5217392/141190491-1ac82f25-a211-4d71-9b59-d8477b2b901b.png)

**Comment by Idhrendur** [comment]
For injecting the character:

> Perhaps an event when the civil war starts.  He would most likely go with Theodora/Irene's side (the democratic faction) due to what he experienced in later Vicky, although he has doubts about the cause.
